apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nodejs-app-helm
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/akshayviola/nodejs-app-helm.git
  secretRef:
    name: flux-system
