apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: helm-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/akshayviola/nodejs-app-helm
  ref:
    branch: main
  secretRef:
    name: flux-system
