apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-kustomization
  namespace: flux-system
spec:
  interval: 10m0s
  path: "./"
  prune: true
  sourceRef:
    kind: GitRepository
    name: helm-repo
  targetNamespace: flux-system
