apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nodejs-app
  namespace: flux-system
spec:
  releaseName: nodejs-app
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: helm-repo
        namespace: flux-system
      interval: 1m
  interval: 5m
  values:
    replicaCount: 1
    image:
      repository: akshay2001a/nodejs-app
      pullPolicy: IfNotPresent
      tag: "latest"
